Modules/TramitesAlcaldia/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['https']],function () {
	Route::get('coordinacioncronograma/tramitesbusqueda', 'TramAlcaldiaCabController@tramitesBusqueda');
	// Route::get('coordinacioncronograma/reportesTramitesExternos', 'TramAlcaldiaCabController@tramitesBusqueda');
});
Route::group(['prefix' => 'tramitesalcaldia', 'middleware' => ['https']],function () {
	Route::get('/', 'TramitesAlcaldiaController@index')->name('tramitesalcaldia.index');
	Route::resource('tramites', 'TramAlcaldiaCabController');
	Route::resource('tipostramites', 'TipoTramiteController', ['except' => ['show', 'destroy']]);


	Route::resource('autorizaciones', 'TramInternoAutorizacionController');
	Route::get('tramitesAutorizacionesjax', 'TramInternoAutorizacionController@tramitesAutorizacionesjax');
	Route::get('descargarFormatoAutorizacion/{cedula}', 'TramInternoAutorizacionController@descargarFormatoAutorizacion');


	Route::get('tipostramitesajax', 'TipoTramiteController@tipostramitesajax');
	Route::resource('areas', 'AreasController', ['except' => ['show', 'destroy']]);
	Route::get('areasajax', 'AreasController@areasajax');

	Route::get('vertramite/{id}', 'TramAlcaldiaCabController@reporte');
	Route::get('ContratoElectronico', 'TramAlcaldiaCabController@PolicyUsoDeMediosElectronicos')->name('contrato');

	Route::get('tramitesdespacho', 'TramAlcaldiaCabController@index3'); //despacho alcaldia
	Route::get('tramitesdespachoatendidosnegados', 'TramAlcaldiaCabController@indexatendidos');
	Route::get('tramitesdespachoatendidosaprobados', 'TramAlcaldiaCabController@indexatendidos');
	// Route::get('tramitesfinalizados', 'TramAlcaldiaCabController@indexdespachados');
	Route::get('consultar_cedula/{cedula}', 'TramAlcaldiaCabController@consultar_cedula');
	Route::get('obtener_ubicacion/{direccion}', 'TramAlcaldiaCabController@obtener_ubicacion');
	Route::get('obtenerbarrios/{parroquia}', 'TramAlcaldiaCabController@obtenerBarrios');

	Route::get('mis-tramites/{cedula}', 'TramAlcaldiaCabController@tramitesCiudadano');
	Route::get('timeline/{id}', 'TramAlcaldiaCabController@timeline');

	Route::get('tramitesrespondidos', 'TramAlcaldiaCabController@index2')->name('tramitesrespondidos');
	Route::get('tramitesfinalizados', 'TramAlcaldiaCabController@indexFinalizados');
	Route::get('tramitesrevision', 'TramAlcaldiaCabController@indexRevision');
	Route::get('tramitesrevisionatender', 'TramAlcaldiaCabController@indexRevisionAtender');
	Route::get('tramitesenrevision', 'TramAlcaldiaCabController@revisionAnalista');
	Route::get('tramitesrevisar', 'TramAlcaldiaCabController@tramitesRevisar')->name('tramites.revisar');
	Route::get('tramitesrevisarajax', 'TramAlcaldiaCabController@tramitesRevisarAjax')->name('tramites.revisar.ajax');
	Route::get('tramitesdevueltos', 'TramAlcaldiaCabController@indexDevueltos');
	Route::get('calcular_fecha_despachar/{tramite}/{fecha_inicial}', 'TramAlcaldiaCabController@calcular_fecha_despachar');

	Route::get('despachartramite', 'TramAlcaldiaCabController@editdespacho');
	Route::get('finalizartramite', 'TramAlcaldiaCabController@editFinalizar')->name('tramite.editfinalizar');
	Route::post('devolver/{id}/{timeline}', 'TramAlcaldiaCabController@devolver');
	
	Route::get('obtenerusuario/{id}', 'TramAlcaldiaCabController@obtenerUsuario');
	
	// DASHBOARD
	Route::get('tramitesexternosdashboard/{desde}/{hasta}', 'DashboardTramitesController@tramitesExternos');
	Route::get('tramitesinternosdashboard/{desde}/{hasta}', 'DashboardTramitesController@tramitesInternos');
	Route::get('tramitesestadosajax', 'DashboardTramitesController@tramitesEstadosAjax')->name('tramites.estados');

	Route::get('asignados', 'AsignarAnalistasController@asignados');
	Route::get('asignadoscontestados', 'AsignarAnalistasController@asignadosContestados');
	Route::get('asignadosajax', 'AsignarAnalistasController@asignadosAjax')->name('asignados.ajax');
	Route::post('asignaranalista/{id}', 'AsignarAnalistasController@asignarAnalista');
	Route::post('guardarinformeanalista/{id}', 'AsignarAnalistasController@guardarInformeAnalista');

	Route::get('tramitesexternos', 'TramAlcaldiaCabController@tramites');
	Route::get('tramitesexternosajax', 'TramAlcaldiaCabController@tramitesAjax')->name('tramites.externos.ajax');
	Route::get('tramitesexternosportal', 'TramAlcaldiaCabController@tramitesPortal');

	Route::get('tramitesbusqueda', 'TramAlcaldiaCabController@tramitesBusqueda');
	Route::get('tramitesingresadosajax', 'TramAlcaldiaCabController@tramitesBusquedaAjax')->name('tramites.busqueda.ajax');

	/**TRÁMITES INTERNOS */
	Route::get('tramitesinternos/recibidos', 'TramitesInternosController@recibidos')->name('tramites.recibidos');
	Route::get('tramitesinternos/copia', 'TramitesInternosController@conCopia')->name('tramites.copia');
	Route::get('tramitesinternos/contestados', 'TramitesInternosController@contestados')->name('tramites.contestados');
	Route::get('tramitesinternos/archivados', 'TramitesInternosController@archivados')->name('tramites.archivados');
	Route::get('tramitesinternos/borradores', 'TramitesInternosController@borradores')->name('tramites.borradores');
	Route::get('tramitesinternos/oficios', 'TramitesInternosController@oficios')->name('oficios.index');
	Route::get('tramitesinternos/oficiosajax', 'TramitesInternosController@oficiosAjax')->name('oficios.ajax');
	Route::get('tramitesinternoshistorial/{id}', 'TramitesInternosController@show')->name('internos.show');
	Route::get('agregarhistorial', 'TramitesInternosController@agregarHistorial');

	Route::post('eliminarBorrador', 'TramitesInternosController@eliminarBorrador');

	Route::resource('tramitesinternos', 'TramitesInternosController');
	Route::get('indexajax', 'TramitesInternosController@indexajax')->name('tramites.ajax');

	Route::get('copiaedit/{id}', 'TramitesInternosController@copiaEdit')->name('copia.edit');

	Route::get('revisionedit/{id}', 'TramitesInternosController@revisionEdit')->name('revision.edit');
	Route::put('guardarrevision/{id}', 'TramitesInternosController@guardarRevision')->name('revision.store');
	Route::post('desvinculartramiteinterno/{id}', 'TramitesInternosController@desvincularTramiteInterno');
	Route::post('archivartramiteinterno/{id}', 'TramitesInternosController@archivarTramite');

	// Route::put('archivartramite/{id}', 'TramitesInternosController@archivarTramite');
	Route::get('consultardireccion', 'TramitesInternosController@consultardireccion');

	////firma electronica
	Route::post('generarDocumento', 'TramitesInternosController@generarDocumento')->name('generarDocumento');
	Route::get('generarDocumento', 'TramitesInternosController@generarDocumento')->name('generarDocumento');
	Route::get('validarDocumento', 'TramitesInternosController@validarDocumento')->name('validarDocumento');
	Route::post('generarCodigo', 'TramitesInternosController@generarCodigo')->name('generarCodigo');

	Route::get('reservados', 'TramAlcaldiaProcesosController@tramitesReservados');
	Route::get('tramitesreservadosajax', 'TramAlcaldiaProcesosController@tramitesReservadosAjax');
	Route::get('concopia', 'TramAlcaldiaProcesosController@conCopia');
	Route::get('tramitesconcopiasajax', 'TramAlcaldiaProcesosController@tramitesConCopiasAjax');
	Route::post('desvinculartramite/{id}', 'TramAlcaldiaProcesosController@desvincularTramite');
	Route::post('solicitarinforme/{id}', 'TramAlcaldiaProcesosController@solicitarInforme')->name('solicitarinforme');
	Route::post('notificarcoordinador/{id}/{direccion}', 'TramAlcaldiaProcesosController@notificarCoordinador');
	Route::post('enviaraprobacion/{id}', 'TramAlcaldiaProcesosController@enviarAprobacion');
	Route::get('solicitudesinforme', 'TramAlcaldiaProcesosController@solicitudesInforme');
	Route::post('guardarinforme/{id}', 'TramAlcaldiaProcesosController@guardarInforme');
	Route::post('devolverdirector/{id}/{id_direccion}', 'TramAlcaldiaProcesosController@devolverDirector');
	Route::post('reservartramite', 'TramAlcaldiaProcesosController@reservarTramite');
	Route::post('finalizartramitedirector/{id}', 'TramAlcaldiaProcesosController@finalizarTramiteDirector');
	Route::post('finalizarimcompleto/{id}', 'TramAlcaldiaProcesosController@finalizarImcompleto');
	Route::get('obtenertipostramite/{area}', 'TramAlcaldiaProcesosController@obtenerTiposTramite');
	Route::post('eliminararchivotramite', 'TramAlcaldiaProcesosController@eliminarArchivo');
	Route::post('subirarchivotramite', 'TramAlcaldiaProcesosController@subirArchivo')->name('subirarchivo.tramite');
	Route::post('subiralcancetramite', 'TramAlcaldiaProcesosController@subirArchivoAlcance')->name('subiralcance.tramite');
	Route::post('subiracuerdo', 'TramAlcaldiaProcesosController@subirArchivoAcuerdo')->name('subiracuerdo.tramite');
	Route::post('eliminaracuerdo', 'TramAlcaldiaProcesosController@eliminarArchivoAcuerdo');
	Route::get('cargaracuerdo/{cedula}', 'TramAlcaldiaProcesosController@cargarArchivoAcuerdo');
	Route::post('eliminararchivoalcance', 'TramAlcaldiaProcesosController@eliminarArchivoAlcance');
	Route::post('enviarrespuestaciudadano/{id}', 'TramAlcaldiaProcesosController@enviarRespuestaCiudadano');
	Route::post('finalizarconpago/{id}', 'TramAlcaldiaProcesosController@finalizarConPago');
	Route::post('enviardonacion/{id}', 'TramAlcaldiaProcesosController@enviarDonacion');
	Route::post('devolverventanilla/{id}', 'TramAlcaldiaProcesosController@devolverVentanilla');

	Route::get('tramitesingresados', 'TramAlcaldiaProcesosController@tramitesIngresadoPortal');

Modules/TramitesAlcaldia/Resources/views/agendartramite.blade.php
<?php
if(!isset($nobloqueo))
?>
@extends(Input::has("menu") ? 'layout_basic_no_head':'layout' )

@section ('titulo') Agendar Trámite @stop

<style>
    .loader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 90%;
        z-index: 9999;
        opacity: .8;
        background: url({{ asset('img/loading35.gif') }}) 50% 50% no-repeat rgb(249,249,249);
    }

    .disabled {
        pointer-events: none !important;
        color: #AAA !important;
        background: #F5F5F5 !important;
    }
</style>

@section ('contenido')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="imgback">
                    <h1>Agendar trámite</h1>
                </div>

                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <div class="">
                            <a href="{{ route('tramites.index') }}" class="btn btn-primary "><i class="fa fa-align-justify"></i> Todos</a>
                            <a href="{{ route('tramites.create') }}" class="btn btn-default ">Volver</a>
                        </div>

                        @if($errors->all())
                            <script>
                            $(document).ready(function() {
                                toastr["error"]($("#diverror").html());    
                            });
                            </script>
                            <div class="alert alert-danger" style="text-align: left;" id='diverror'>
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <h4>Error!</h4>
                            <div id="diverror">
                                <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                                </ul>
                            </div>
                            </div>
                        @endif

                        @if (Session::has("warning"))
                            <script>
                                $(document).ready(function() {
                                    toastr["warning"]("{{ Session::get('warning') }}");
                                });
                            </script>
                            <div class="alert alert-warning">⚠ Advertencia ⚠ <br>{{ Session::get('warning') }}</div>
                        @endif
                    </div>

                    <div class="ibox-content">
                        {!! Form::open(array('route' => 'agenda.store','role'=>'form' , 'id'=>'form-tram','class'=>'form-horizontal', 'files' => true)) !!}
                            <div class="form-group">
                                <div class="loader" id="position" style="diplay: none;"></div>
                                {!! Form::hidden('ubicacion', null, ['id' => 'ubicacion']) !!}
                            </div>
                        
                            @foreach($objetos as $i => $campos) 
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-2">
                                        <div class="form-group">
                                            {!! Form::label($campos->Nombre, $campos->Descripcion, []) !!}    
                                            @if($campos->Tipo=="select")
                                                {!! Form::select($campos->Nombre,$campos->Valor, Input::old($campos->Nombre) ? Input::old($campos->Nombre) :
                                                ($campos->ValorAnterior !="Null") ? $campos->ValorAnterior : Input::old($campos->Nombre), array('class' =>
                                                "form-control ".$campos->Clase)) !!}
                                            @elseif($campos->Tipo=="textarea2")
                                                {!! Form::textarea($campos->Nombre, Input::old($campos->Valor) , array('class' => 'form-control ' .
                                                $campos->Clase ,'placeholder'=>'Ingrese '.$campos->Descripcion, 'rows' => 3)) !!}
                                            @elseif($campos->Tipo=="datetimetext")
                                                <div id="date_{{$campos->Nombre}}" class="input-group datetime">
                                                    <span class="input-group-addon">
                                                        <span class="glyphicon glyphicon-calendar"></span>
                                                    </span>
                                    
                                                    {!! Form::text($campos->Nombre, $campos->Valor , array(
                                                    'data-placement' =>'top',
                                                    'data-toogle'=>'tooltip',
                                                    'class' => 'form-control datefecha '.$campos->Clase,
                                                    'placeholder'=>$campos->Descripcion,
                                                    $campos->Nombre,
                                                    )) !!}
                                                </div>
                                            @elseif($campos->Tipo=="file")
                                                {!! Form::file($campos->Nombre, array('class' => 'form-control '.$campos->Clase)) !!}
                                            @else
                                                {!! Form::text($campos->Nombre, $campos->ValorAnterior!="Null" ? $campos->ValorAnterior :
                                                Input::old($campos->Valor) , array('class' => 'form-control '.$campos->Clase,'placeholder'=>'Ingrese '.$campos->Descripcion)) !!}
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                                
                            <div class="row">
                                <div class="col-xs-10 col-md-8 col-md-offset-2">
                                    <div style="width: 600px; height: 400px;" id="map_canvas"></div>
                                </div>
                            </div>

                            {!! Form::submit("Guardar", array('id'=>'btn_guardar','class' => 'btn btn-primary', 'style' => 'float:right' )) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @include("vistas.includes.mainjs")
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDy1ViaIr_ziZYThMeiNuvrZK7pUb7X_SI&libraries=places"></script>
    <script src="{{ asset('js/tramites-agenda.js') }}"></script>
@endsection

Modules/TramitesAlcaldia/Resources/views/index.blade.php
@extends('tramitesalcaldia::layouts.master')

@section('contenido')
<script type="text/javascript">
    $(document).ready(function(){
    //            $('.contact-box').each(function() {
    //                animationHover(this, 'pulse');
    //            });
                        
    //    $('.gallery-slideshow').slideshow({
    //    // default: 2000
    //    interval: 3000,
    //    // default: 500
    //    width: 580,
    //    // default: 350
    //    height: 350
    //    });
    //    $('#myModal').modal('toggle');
    });
          
   </script>   
@stop

Modules/TramitesAlcaldia/Resources/views/modaltramites.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="modalTramites">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">TRÁMITES EXTERNOS</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <table class="table table-striped table-bordered table-hover display" id="tabla-tramites" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Número de trámite</th>
                                <th>Fecha de ingreso</th>
                                <th>Tipo de trámite</th>
                                <th>Remitente</th>
                                <th>Dirección a atender</th>
                                {{-- <th>Con copia</th> --}}
                                <th>Analistas asignados</th>
                                <th>Fecha estimada de finalización</th>
                                {{-- <th>Adjunto</th> --}}
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

Modules/TramitesAlcaldia/Resources/views/recibo.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Comprobante</title>
</head>

<body>


  <style>
    .x10 {
      font-size: 11px;
    }

    .x20 {
      font-size: 14px;
    }

    .x23 {
      font-size: 12px;
    }

    .centrado {
      text-align: center;
    }
  </style>

  <div id="general">
    <div class="centrado x23" style="padding-bottom: 10px;">
      <b>GOBIERNO AUTÓNOMO DESCENTRALIZADO
        MUNICIPAL DEL CANTÓN MANTA</b><br>



    </div>
    <div id="contenedor">
      <table width="100%" cellpadding="0" cellspacing="0" align="center" class="table">
        <tbody>
          <tr>
            <td align="center"> <span class="x20">No. Trámite asignado</span></td>
          </tr>
          <tr>
            <td align="center"><span class="x20"> <b>{{$tabla->numtramite}}</b></span></td>
          </tr>
          <tr>
            <td align="center"><span class="x20">
                @php
                if($tabla->tipo==null){
                echo 'Secretaria general';
                }else{
                echo 'Trámite municipal';
                }
                @endphp
              </span></td>
          <tr>
          <tr>
            <td align="center"><span class="x20"><br></span></td>
          </tr>
        </tbody>
      </table>
      <table width="100%" cellpadding="0" cellspacing="0" align="center" class="table">
        <tbody>
          <tr>
            <td align="center"> <span class="x20"><b>Remitente:</b></span></td>
          </tr>
          <tr>
            <td align="center"><span class="x20">{{$tabla->cedula_remitente}}</span></td>
          </tr>
          <tr>
            <td align="center"><span class="x10">{{$tabla->remitente}}</span></td>
          <tr>


          <tr>
            <td align="center"><span class="x20"><br></span></td>
          </tr>
          <tr>
            <td align="center"> <span class="x20"><b>Fecha y hora de entrega:</b></span></td>
          </tr>
          <tr>
            <td align="center"><span class="x20">{{fechas(600,$tabla->fecha_ingreso)}}</span></td>
          </tr>
          <tr>
            <td align="center"><span class="x20">{{fechas(1200,$tabla->create_at)}}</span></td>
          <tr>
          <tr>
            <td align="center"><span class="x20"><br></span></td>
          </tr>


          <?php
          if (isset($anexos[0])) {
            # code...
            echo '<tr><td align="center"><span class="x20"><b>Anexos:</b></span></td></tr>';
          }
          foreach ($anexos as $key => $value) {
            # code...
            echo  '<tr><td align="center"><span class="x20">' . $value->nombre . ' <b>(' . $value->hojas . ' h.)</b></span></td></tr>';
          }
          ?>
        </tbody>
      </table>

    </div>
    <div class="centrado">
      <p class="x20">
        Puede revisar la trazabilidad del su solicitud
        en: https://portalciudadano.manta.gob.ec/
      </p>
    </div>

    <script type="text/javascript">
      function printHTML() {
        if (window.print) {
          window.print();
          setTimeout(() => {

            window.close();
          }, 2000);
        }
      }
      document.addEventListener("DOMContentLoaded", function(event) {
        printHTML();
      });
    </script>
</body>

</html>